version: 2
updates:
  - package-ecosystem: docker
    directory: nginx
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: portainer
    schedule:
      interval: weekly
