stages:
  - deploy

include:
  - project: 'rickselby-linode-setup/nginx-proxy'
    file: '/.gitlab-ci-template.yml'

deploy:
  extends: .docker-template
  stage: deploy
  script:
    - eval $COMPOSE_COMMAND build --pull
    - eval $COMPOSE_COMMAND pull 
    - eval $COMPOSE_COMMAND down
    - eval $COMPOSE_COMMAND up -d
  only:
    - master

