version: '2.4'

services:
  nginx:
    container_name: portainer-web
    build: nginx/
    restart: always
    environment:
      VIRTUAL_HOST: portainer.djomp.co.uk
      LETSENCRYPT_HOST: portainer.djomp.co.uk
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

  portainer:
    container_name: portainer-app
    build: portainer/
    restart: always
    command: --host=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:

networks:
  default:
    name: portainer
